
class ArabicStrings {
    
    static var ArabicStringsDictionary = [
        "log_in":"تسجيل الدخول",
        "email":"البريد الالكتروني",
        "user_name":"اسم المستخدم",
        "enter_password":"ادخل كلمة المرور",
        "fill_data":"املء كل البيانات اولا",
        "enter_valid_email":"ادخل بريد الكتروني صحيح",
        "ok":"موافق",
        "cancel":"الغاء",
        "going_offline":"هل تريد التوقف الان؟",
        "please_wait":"برجاء الانتظار...",
        "check_internet":"تحقق من اتصال الانترنت",
        "my_profile":"الملف الشخصي",
        "orders_history":"الرحلات السابقة",
        "profit":"الربح",
        "language":"تغيير اللغة",
        "personal_info":"البيانات الشخصية",
        "vehicle_info":"بيانات السيارة",
        "dead_line":"الوقت",
        "second":"ث",
        "fees":"التكلفة",
        "sar":"ريال",
        "from":"من",
        "to":"الى",
        "sent_to":"مرسل ل",
        "accept":"قبول",
        "write_suggest":"او\nاقترح تكلفة",
        "send":"ارسال",
        "enter_fees":"ادخل التكلفة المقترحة اولا",
        "enter_greater_no":"ادخل تكلفة اكبر من تكلفة الرحلة",
        "write_msg":"اكتب رسالة اولا",
        "type_msg":"اكتب رسالة",
        "open":"قيد التنفيذ",
        "excuted":"تم التنفيذ",
        "cancelled":"ملغي",
        "start":"ابدا",
        "finish":"انهاء",
        "my_orders_profits":"ربح رحلاتي",
        "income":"الدخل",
        "rest_amount":"القيمة المتبقية",
        "paid_amount":"القيمة المدفوعة",
        "history_date":"التاريخ",
        "change":"تغيير",
        "order":"الطلب",
        "wait_approval":"برجاء انتظار موافقة العميل",
        "approved":"تم قبول تكلفتك المقترحة\nاذهب الي نقطة البدء",
        "disapproved":"للاسف لم يتم قبول التكلفة المقترحة",
        "another_driver_accepted":"للاسف تم القبول من قبل سائق اخر",
        "trip_completed":"الرحلة انتهت",
        "client_cancelled":"العميل قام بانهاء الرحلة",
        "change_language_confirm":"هل تريد تغيير اللغة الى الانجليزية؟",
        "image_alert_title":"اختر صورة",
        "camera":"كاميرا",
        "photo_library":"مكتبة الصور",
        "image_alert_cancel":"الغاء",
        "tripAlertAccpeted":"تم قبول الطلب بالفعل!",
        "phone":"الجوال",
        "category":"الفئة",
        "recommended_places":"الاماكن الموصى بها",
        "calculate":"احسب",
        "invoice":"الفاتورة",
        "total_fees":"القيمة الاجمالية",
        "type":"النوع",
        "promotion":"القيمة الترويجية",
        "our_profit":"ارباحنا",
        "your_profit":"ارباحك",
        "client_phone":"جوال العميل",
        "receiver_phone":"جوال المرسل اليه"
    ]
}
