
class EnglishStrings {
    
    static var EnglishStringsDictionary = [
        "log_in":"LOGIN",
        "email":"E-mail",
        "enter_password":"Enter Password",
        "user_name":"User Name",
        "fill_data":"Please fill all data first",
        "enter_valid_email":"Please enter a valid E-mail",
        "ok":"OK",
        "cancel":"Cancel",
        "going_offline":"Are you sure you want to be offline?",
        "please_wait":"Please Wait...",
        "check_internet":"Please check internet connection",
        "my_profile":"My Profile",
        "orders_history":"Orders History",
        "profit":"Profit",
        "language":"Change Language",
        "personal_info":"Personal Infomation",
        "vehicle_info":"Vehicle Infomation",
        "dead_line":"Deadline",
        "second":"s",
        "fees":"Fees",
        "sar":"SR",
        "from":"From",
        "to":"To",
        "sent_to":"Sent To",
        "accept":"Accept",
        "write_suggest":"OR\nWrite your suggest fees",
        "send":"Send",
        "enter_fees":"Enter suggested fees first",
        "enter_greater_no":"Enter fees greater than trip fees",
        "write_msg":"Write message first",
        "type_msg":"Type message",
        "open":"Open",
        "excuted":"Excuted",
        "cancelled":"Cancelled",
        "start":"START",
        "finish":"FINISH",
        "my_orders_profits":"My Orders Profits",
        "income":"Income",
        "rest_amount":"Rest Amount",
        "paid_amount":"Paid Amount",
        "history_date":"History Date",
        "change":"Change",
        "order":"Order",
        "wait_approval":"Please wait for client approval",
        "approved":"Your offer is approved\nReach the start point",
        "disapproved":"Sorry your offer is disapproved",
        "another_driver_accepted":"Sorry Another driver already accepted",
        "trip_completed":"Your trip is completed",
        "client_cancelled":"Client cancelled trip",
        "change_language_confirm":"Are you sure you want to change language to Arabic?",
        "image_alert_title":"Select Image",
        "camera":"Camera",
        "photo_library":"Photo Library",
        "image_alert_cancel":"Cancel",
        "tripAlertAccpeted":"order is already accepted",
        "phone":"Phone",
        "category":"Category",
        "recommended_places":"Recommended Places",
        "calculate":"CALCULATE",
        "invoice":"Invoice",
        "total_fees":"Total Fees",
        "type":"Type",
        "promotion":"Promotion",
        "our_profit":"Our Profit",
        "your_profit":"Your Profit",
        "client_phone":"Client Phone",
        "receiver_phone":"Receiver Phone"

    ]
}
